import { Language, User, Task } from './types';

export const DICTIONARY = {
  en: {
    title: "Southern Africa Engineering Service Office II",
    subtitle: "Work Calendar System",
    deptName: "Schedule Management System",
    login: "Login",
    register: "Register",
    employeeId: "Employee ID",
    password: "Password",
    name: "Full Name",
    admin: "Admin",
    dashboard: "Dashboard",
    calendar: "Calendar",
    logout: "Logout",
    import: "Import Schedule (CSV)",
    stats: "Statistics",
    myTasks: "My Tasks",
    completionRate: "Completion Rate",
    efficiency: "Efficiency Analysis",
    efficiencyByUser: "Efficiency (By User)",
    totalTasks: "Total Tasks",
    completed: "Completed",
    pending: "Pending",
    edit: "Edit",
    delete: "Delete",
    save: "Save",
    cancel: "Cancel",
    addTask: "Add Task",
    noTasks: "No tasks for this day",
    filterUser: "Filter by User",
    allUsers: "All Users",
    description: "Description",
    category: "Category",
    start: "Start Date",
    end: "End Date",
    status: "Status",
    darkMode: "Dark Mode",
    lightMode: "Light Mode",
    welcome: "Welcome",
    uploadInstruction: "Upload CSV with columns: EmployeeID, Name, Title, Category, Start, End",
    sheetName: "Sheet/Category",
    day: "Day",
    week: "Week",
    month: "Month",
    categoryDistribution: "Task Category Distribution",
    workloadTrend: "14-Day Workload Trend",
    taskAnalysis: "Task Analysis",
    allCaughtUp: "All caught up for this",
    tasksRemaining: "tasks remaining this",
    efficiencyTip: "Your focus is on track. Keep managing your schedule effectively to maintain high efficiency.",
    userManagement: "User Management",
    addUser: "Add User",
    updateUser: "Update User",
    deleteUser: "Delete User",
    role: "Role",
    actions: "Actions",
    exportPdf: "Export PDF Report",
    staffCount: "Staff Count",
    activeTasks: "Active Tasks",
    completedToday: "Completed Today",
    statusExcellent: "Excellent",
    statusNormal: "Normal",
    statusLow: "Low",
    rate: "Rate",
    weekdays: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
    months: ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"],
    noDesc: "No description provided.",
    more: "more",
    confirmDelete: "Are you sure?",
    invalidCredentials: "Invalid ID or Password",
    userExists: "User already exists",
    toggleAuth: ["No account? Register", "Have an account? Login"],
    instruction: "Instruction:",
    csvExample: "Example: 1001, Zhang San, Site Survey, Network, 2024-01-01, 2024-01-02",
    pasteCsvPlaceholder: "Paste CSV content here...",
    importSuccess: "tasks imported successfully.",
    importBtn: "Import",
    period: "Period",
    reportTitle: "Personnel Efficiency Report",
    suggestion: "Suggestion & Conclusion",
    suggestionHigh: "Excellent performance. The team is maintaining high efficiency. Continue the current workflow.",
    suggestionMid: "Good performance. There are some pending tasks. Focus on clearing the backlog to improve the completion rate.",
    suggestionLow: "Efficiency is lower than expected. Please review task allocation and potential bottlenecks.",
    resetPassword: "Reset Password (leave blank to keep current)",
    generatingPdf: "Generating Report...",
    redList: "Honor Roll (Red List)",
    blackList: "Attention List (Black List)",
    redListDesc: "Top performers with highest completion rates.",
    blackListDesc: "Personnel needing improvement or support.",
    reportOverview: "Overview Statistics"
  },
  zh: {
    title: "南非拓二工服处",
    subtitle: "工作日历系统",
    deptName: "日程管理系统",
    login: "登录",
    register: "注册",
    employeeId: "工号",
    password: "密码",
    name: "姓名",
    admin: "管理员",
    dashboard: "管理后台",
    calendar: "工作日历",
    logout: "退出登录",
    import: "导入日程 (CSV/Excel)",
    stats: "统计概览",
    myTasks: "我的任务",
    completionRate: "完成率",
    efficiency: "效率分析",
    efficiencyByUser: "人员效率分析",
    totalTasks: "总任务",
    completed: "已完成",
    pending: "待办",
    edit: "编辑",
    delete: "删除",
    save: "保存",
    cancel: "取消",
    addTask: "新增任务",
    noTasks: "今日无任务",
    filterUser: "筛选人员",
    allUsers: "所有人员",
    description: "详细内容",
    category: "工作分类",
    start: "开始时间",
    end: "结束时间",
    status: "状态",
    darkMode: "黑夜模式",
    lightMode: "白天模式",
    welcome: "欢迎",
    uploadInstruction: "上传CSV文件，列包含：工号, 姓名, 标题, 分类, 开始时间, 结束时间",
    sheetName: "Sheet页/分类",
    day: "日",
    week: "周",
    month: "月",
    categoryDistribution: "任务分类占比",
    workloadTrend: "近14天工作趋势",
    taskAnalysis: "任务详情分析",
    allCaughtUp: "本周期任务已全部完成",
    tasksRemaining: "本周期剩余任务数",
    efficiencyTip: "您的工作状态良好，请继续保持高效的时间管理。",
    userManagement: "用户管理",
    addUser: "添加用户",
    updateUser: "更新用户",
    deleteUser: "删除用户",
    role: "角色",
    actions: "操作",
    exportPdf: "导出PDF分析报告",
    staffCount: "员工人数",
    activeTasks: "活跃任务",
    completedToday: "今日完成",
    statusExcellent: "优秀",
    statusNormal: "正常",
    statusLow: "较低",
    rate: "完成率",
    weekdays: ['日', '一', '二', '三', '四', '五', '六'],
    months: ["一月", "二月", "三月", "四月", "五月", "六月", "七月", "八月", "九月", "十月", "十一月", "十二月"],
    noDesc: "暂无详细描述",
    more: "更多",
    confirmDelete: "确认删除?",
    invalidCredentials: "账号或密码错误",
    userExists: "用户已存在",
    toggleAuth: ["没有账号? 注册", "已有账号? 登录"],
    instruction: "说明:",
    csvExample: "示例: 1001, 张三, 站点勘测, 网络优化, 2024-01-01, 2024-01-02",
    pasteCsvPlaceholder: "在此粘贴CSV内容...",
    importSuccess: "条任务导入成功。",
    importBtn: "导入",
    period: "周期",
    reportTitle: "人员效率分析报告",
    suggestion: "建议与结论",
    suggestionHigh: "整体表现优秀。团队保持了较高的工作效率，请继续保持当前的工作流程。",
    suggestionMid: "表现良好。存在少量待办任务，建议关注未完成事项，清理积压任务以提升完成率。",
    suggestionLow: "效率较低。建议重新评估任务分配情况，查找工作瓶颈并进行调整。",
    resetPassword: "重置密码 (留空则保持不变)",
    generatingPdf: "正在生成报告...",
    redList: "今日红榜 (优秀榜)",
    blackList: "今日黑榜 (关注榜)",
    redListDesc: "完成率最高且任务量饱满的标杆人员。",
    blackListDesc: "完成率较低或存在延期风险的人员。",
    reportOverview: "数据概览"
  }
};

export const INITIAL_USERS: User[] = [
  { id: '1', employeeId: 'admin', name: 'System Admin', role: 'admin', password: 'admin123', color: '#EF4444' },
  { id: '2', employeeId: '1001', name: 'Zhang San', role: 'user', password: '123', color: '#3B82F6' },
  { id: '3', employeeId: '1002', name: 'Li Si', role: 'user', password: '123', color: '#10B981' },
];

export const INITIAL_TASKS: Task[] = [
  {
    id: 't1',
    employeeId: '1001',
    category: 'Network Optimization',
    title: 'Site Survey',
    description: 'Survey site A for 5G deployment',
    startDate: new Date().toISOString().split('T')[0],
    endDate: new Date().toISOString().split('T')[0],
    status: 'pending'
  },
  {
    id: 't2',
    employeeId: '1002',
    category: 'Maintenance',
    title: 'Server Check',
    description: 'Routine maintenance of core network',
    startDate: new Date().toISOString().split('T')[0],
    endDate: new Date().toISOString().split('T')[0],
    status: 'completed'
  }
];