
import { Language, User, Task } from './types';

export const DICTIONARY = {
  en: {
    title: "Southern Africa Engineering Service Office II",
    titleMobile: "Southern Africa ESO II",
    taskTitle: "Task Name",
    subtitle: "Work Calendar System",
    deptName: "Schedule Management System",
    login: "Login",
    register: "Register",
    employeeId: "Employee ID",
    password: "Password",
    name: "Full Name",
    admin: "Admin",
    user: "User",
    dashboard: "Dashboard",
    calendar: "Calendar",
    logout: "Logout",
    import: "Data Management",
    stats: "Stats Panel",
    statsOverview: "Stats Overview",
    myTasks: "My Tasks",
    completionRate: "Completion Rate",
    efficiency: "Efficiency Analysis",
    efficiencyByUser: "Efficiency (By User)",
    totalTasks: "Total Tasks",
    completed: "Completed",
    pending: "Pending",
    edit: "Edit",
    delete: "Delete",
    save: "Save",
    cancel: "Cancel",
    addTask: "Add Task",
    noTasks: "No tasks for this day",
    filterUser: "Filter by User",
    allUsers: "All Users",
    description: "Description",
    category: "Category",
    start: "Start Date",
    end: "End Date",
    status: "Status",
    overdue: "Overdue",
    darkMode: "Dark Mode",
    lightMode: "Light Mode",
    welcome: "Welcome Login",
    uploadInstruction: "Supports .xlsx, .xls, .csv formats. Columns: EmployeeID, Name, Title, Category, Description, StartDate, EndDate",
    sheetName: "Sheet/Category",
    day: "Day",
    week: "Week",
    month: "Month",
    categoryDistribution: "Task Category Distribution",
    workloadTrend: "14-Day Workload Trend",
    taskAnalysis: "Task Analysis",
    allCaughtUp: "All caught up for this",
    tasksRemaining: "tasks remaining this",
    efficiencyTip: "Your focus is on track. Keep managing your schedule effectively to maintain high efficiency.",
    userManagement: "User Management",
    addUser: "Add User",
    updateUser: "Update User",
    deleteUser: "Delete User",
    role: "Role",
    actions: "Actions",
    exportPdf: "Export Image Report",
    staffCount: "Staff Count",
    activeTasks: "Active Tasks",
    completedToday: "Completed Today",
    statusExcellent: "Excellent",
    statusNormal: "Normal",
    statusLow: "Low",
    rate: "Rate",
    weekdays: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
    months: ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"],
    noDesc: "No description provided.",
    more: "more",
    confirmDelete: "Are you sure?",
    invalidCredentials: "Invalid ID or Password",
    userExists: "User already exists",
    toggleAuth: ["No account? Register", "Have an account? Login"],
    instruction: "Instruction:",
    csvExample: "Example: 1001, Zhang San, Site Survey, Network, Survey site A, 2024-01-01, 2024-01-02",
    pasteCsvPlaceholder: "Parsed content will appear here...",
    importSuccess: "tasks imported successfully.",
    importBtn: "Import",
    period: "Period",
    reportTitle: "Personnel Efficiency Report",
    suggestion: "Suggestion & Conclusion",
    suggestionHigh: "Excellent performance. The team is maintaining high efficiency. Continue the current workflow.",
    suggestionMid: "Good performance. There are some pending tasks. Focus on clearing the backlog to improve the completion rate.",
    suggestionLow: "Efficiency is lower than expected. Please review task allocation and potential bottlenecks.",
    resetPassword: "Reset Password (leave blank to keep current)",
    generatingPdf: "Generating Image...",
    redList: "Honor Roll (Red List)",
    blackList: "Attention List (Black List)",
    redListDesc: "Top performers with highest completion rates.",
    blackListDesc: "Personnel needing improvement or support.",
    reportOverview: "Overview Statistics",
    uploadLabel: "Upload File (Excel/CSV)",
    clickToUpload: "Click to upload .xlsx, .xls or .csv",
    clickToReplace: "Click to replace file",
    previewLabel: "File Content Preview",
    orPaste: "Or Paste CSV Content",
    responsiblePerson: "Responsible Person",
    firstLoginSetup: "First Login Setup",
    setNewPassword: "Set New Password",
    confirmPassword: "Confirm Password",
    passwordMismatch: "Passwords do not match",
    autoCreatedUser: "Auto-created user found from import.",
    usersCreated: "new users created automatically.",
    tasksRemaining_day: "tasks remaining today",
    tasksRemaining_week: "tasks remaining this week",
    tasksRemaining_month: "tasks remaining this month",
    allCaughtUp_day: "All tasks completed today!",
    allCaughtUp_week: "All tasks completed this week!",
    allCaughtUp_month: "All tasks completed this month!",
    noTasksScheduled: "No tasks scheduled",
    loginTitle: "Southern Africa Engineering Service Office II Schedule Management System",
    loginDesc: "Efficiently manage team tasks, track performance, and generate reports.",
    feature1: "Smart Calendar",
    feature1Desc: "Visual timeline of all team activities.",
    feature2: "Efficiency Stats",
    feature2Desc: "Real-time analysis of completion rates.",
    feature3: "One-Click Reports",
    feature3Desc: "Generate PDF reports instantly.",
    dropToDelete: "Drop here to delete",
    late: "Late",
    exportData: "Export Data",
    exportDesc: "Download your schedule data in standard formats.",
    exportExcel: "Export to Excel",
    exportIcs: "Export to ICS",
    excelDesc: ".xlsx format (Full Data)",
    icsDesc: "Calendar format (Outlook/Google)",
    importRestricted: "Import functionality is restricted to administrators.",
    noActiveTasks: "No active tasks for this period.",
    noData: "No data available for analysis.",
    systemReportFooter: "System Generated Report • ZTE Schedule Management System • Confidential",
    filterCategory: "Category",
    filterStatus: "Status",
    all: "All",
    overdueAnalysis: "Overdue Analysis",
    mostOverdue: "Most Overdue Tasks",
    highestOverdueRate: "Highest Overdue Rate",
    anomalyDetection: "Anomaly Detection",
    stagnantTasks: "Long-term Stagnant",
    overloadedStaff: "Overloaded Staff",
    abnormalDesc: "Pending > 7 days or High Backlog (>5 tasks)",
    longPending: "Stagnant (>1 Week)",
    severelyOverdue: "Severely Overdue",
    highBacklog: "High Backlog (>5)",
    overdueCount: "Count",
    overdueRate: "Rate",
    batchMode: "Batch Management",
    deleteSelected: "Delete Selected",
    confirmBatchDelete: "Are you sure you want to delete these tasks?",
    analysisReport: "Comprehensive Efficiency Analysis",
    dimPersonnel: "Personnel Dimension",
    dimTime: "Time Dimension",
    dimCategory: "Category Dimension",
    reportGeneratedOn: "Report Generated On",
    generatedBy: "Generated By",
    analysisIntro: "This report provides a multi-dimensional analysis of team performance.",
    personnelAnalysis: "Personnel Analysis",
    timeAnalysis: "Time Analysis",
    categoryAnalysis: "Category Analysis",
    dataManagement: "Data Management",
    batchManage: "Batch Manage",
    selectAll: "Select All",
    taskDetailList: "Personnel Task Details",
    searchTasks: "Search tasks...",
    notifications: "Notifications",
    noNotifications: "No new notifications",
    markAllRead: "Mark all as read",
    taskAssigned: "New Task Assigned",
    taskUpdated: "Task Updated",
    taskOverdue: "Task Overdue",
    taskUpcoming: "Upcoming Task",
    taskDeleted: "Task Deleted",
    userCompletedTask: "Staff Completed Task",
    userUpdatedTask: "Staff Updated Task",
    dueTomorrow: "is due tomorrow.",
    isOverdue: "is overdue!",
    accountPending: "Account pending approval.",
    accountRejected: "Account registration rejected.",
    sessionLimit: "Max sessions (3) reached.",
    approve: "Approve",
    reject: "Reject",
    pendingApproval: "Pending Approval",
    userStatus: "Status",
    resetSessions: "Reset Sessions",
    sessions: "Sessions",
    regSuccessWait: "Registration successful! Please wait for admin approval.",
    changeRole: "Change Role",
    userRole: "User Role",
    // Comments
    tabDetails: "Details",
    tabComments: "Feedback",
    comments: "Manager Feedback",
    noComments: "No feedback yet.",
    writeComment: "Write a comment...",
    send: "Send",
    postedBy: "Posted by",
    dailyOverdueSummaryTitle: "Daily Overdue Summary",
    dailyOverdueSummaryBody: (count: number) => `As of now, you have ${count} tasks overdue. Please handle them promptly.`,
    passwordChangedRelogin: "Password changed successfully. Please login again.",
    sessionExpired: "Session expired due to inactivity. Please login again.",
  },
  zh: {
    title: "南非拓二工服处",
    titleMobile: "南非拓二工服处",
    taskTitle: "任务名称",
    subtitle: "工作日历系统",
    deptName: "日程管理系统",
    login: "登录",
    register: "注册",
    employeeId: "工号",
    password: "密码",
    name: "姓名",
    admin: "管理员",
    user: "普通用户",
    dashboard: "管理后台",
    calendar: "工作日历",
    logout: "退出登录",
    import: "数据管理",
    stats: "统计面板",
    statsOverview: "统计概览",
    myTasks: "我的任务",
    completionRate: "完成率",
    efficiency: "效率分析",
    efficiencyByUser: "人员效率分析",
    totalTasks: "总任务",
    completed: "已完成",
    pending: "待办",
    edit: "编辑",
    delete: "删除",
    save: "保存",
    cancel: "取消",
    addTask: "新增任务",
    noTasks: "今日无任务",
    filterUser: "筛选人员",
    allUsers: "所有人员",
    description: "详细内容",
    category: "工作分类",
    start: "开始时间",
    end: "结束时间",
    status: "状态",
    overdue: "已逾期",
    darkMode: "黑夜模式",
    lightMode: "白天模式",
    welcome: "欢迎登录",
    uploadInstruction: "支持 .xlsx, .xls, .csv 格式。数据列需包含：工号, 姓名, 标题, 分类, 描述, 开始时间, 结束时间",
    sheetName: "Sheet页/分类",
    day: "日",
    week: "周",
    month: "月",
    categoryDistribution: "任务分类占比",
    workloadTrend: "近14天工作趋势",
    taskAnalysis: "任务详情分析",
    allCaughtUp: "本周期任务已全部完成",
    tasksRemaining: "本周期剩余任务数",
    efficiencyTip: "您的工作状态良好，请继续保持高效的时间管理。",
    userManagement: "用户管理",
    addUser: "添加用户",
    updateUser: "更新用户",
    deleteUser: "删除用户",
    role: "角色",
    actions: "操作",
    exportPdf: "导出图片报告",
    staffCount: "员工人数",
    activeTasks: "活跃任务",
    completedToday: "今日完成",
    statusExcellent: "优秀",
    statusNormal: "正常",
    statusLow: "较低",
    rate: "完成率",
    weekdays: ['日', '一', '二', '三', '四', '五', '六'],
    months: ["一月", "二月", "三月", "四月", "五月", "六月", "七月", "八月", "九月", "十月", "十一月", "十二月"],
    noDesc: "暂无详细描述",
    more: "更多",
    confirmDelete: "确认删除?",
    invalidCredentials: "账号或密码错误",
    userExists: "用户已存在",
    toggleAuth: ["没有账号? 注册", "已有账号? 登录"],
    instruction: "说明:",
    csvExample: "示例: 1001, 张三, 站点勘测, 网络优化, 站点A详细勘测任务, 2024-01-01, 2024-01-02",
    pasteCsvPlaceholder: "解析后的内容将显示在这里...",
    importSuccess: "条任务导入成功。",
    importBtn: "导入",
    period: "周期",
    reportTitle: "人员效率分析报告",
    suggestion: "建议与结论",
    suggestionHigh: "整体表现优秀。团队保持了较高的工作效率，请继续保持当前的工作流程。",
    suggestionMid: "表现良好。存在少量待办任务，建议关注未完成事项，清理积压任务以提升完成率。",
    suggestionLow: "效率较低。建议重新评估任务分配情况，查找工作瓶颈并进行调整。",
    resetPassword: "重置密码 (留空则保持不变)",
    generatingPdf: "正在生成图片...",
    redList: "今日红榜 (优秀榜)",
    blackList: "今日黑榜 (关注榜)",
    redListDesc: "完成率最高且任务量饱满的标杆人员。",
    blackListDesc: "完成率较低或存在延期风险的人员。",
    reportOverview: "数据概览",
    uploadLabel: "上传文件 (Excel/CSV)",
    clickToUpload: "点击上传 .xlsx, .xls 或 .csv 文件",
    clickToReplace: "点击更换文件",
    previewLabel: "文件内容预览",
    orPaste: "或直接粘贴 CSV 内容",
    responsiblePerson: "责任人",
    firstLoginSetup: "First Login Setup",
    setNewPassword: "Set New Password",
    confirmPassword: "Confirm Password",
    passwordMismatch: "两次输入的密码不一致",
    autoCreatedUser: "发现导入数据中存在未注册用户",
    usersCreated: "名新用户已自动创建。",
    tasksRemaining_day: "本日剩余任务数",
    tasksRemaining_week: "本周剩余任务数",
    tasksRemaining_month: "本月剩余任务数",
    allCaughtUp_day: "本日任务已全部完成",
    allCaughtUp_week: "本周任务已全部完成",
    allCaughtUp_month: "本月任务已全部完成",
    noTasksScheduled: "本周期无计划任务",
    loginTitle: "南非拓二工服处日程管理系统",
    loginDesc: "高效管理团队任务，实时追踪绩效，一键生成分析报告。",
    feature1: "智能日历",
    feature1Desc: "可视化展示团队工作时间轴。",
    feature2: "效率分析",
    feature2Desc: "实时统计任务完成率与工作状态。",
    feature3: "一键报表",
    feature3Desc: "快速导出专业的PDF工作简报。",
    dropToDelete: "松开以删除",
    late: "逾期",
    exportData: "导出数据",
    exportDesc: "下载标准格式的日程数据。",
    exportExcel: "导出 Excel",
    exportIcs: "导出 ICS 日历",
    excelDesc: ".xlsx 格式 (完整数据)",
    icsDesc: "日历格式 (Outlook/Google)",
    importRestricted: "导入功能仅限管理员使用。",
    noActiveTasks: "本周期无活跃任务。",
    noData: "暂无数据可用于分析。",
    systemReportFooter: "系统生成报告 • 南非拓二工服处日程管理系统 • 内部资料",
    filterCategory: "分类",
    filterStatus: "状态",
    all: "全部",
    overdueAnalysis: "责任人逾期分析",
    mostOverdue: "逾期数量最多",
    highestOverdueRate: "逾期率最高",
    anomalyDetection: "异常任务识别",
    stagnantTasks: "长期停滞任务",
    overloadedStaff: "人员积压预警",
    abnormalDesc: "监控超过一周未更新或积压超过5个任务的人员。",
    longPending: "停滞 (>1周)",
    severelyOverdue: "严重逾期",
    highBacklog: "积压过多 (>5)",
    overdueCount: "逾期数",
    overdueRate: "逾期率",
    batchMode: "批量管理",
    deleteSelected: "删除选中项",
    confirmBatchDelete: "确认删除选中的任务？",
    analysisReport: "综合效率分析报告",
    dimPersonnel: "人员维度",
    dimTime: "时间维度",
    dimCategory: "分类维度",
    reportGeneratedOn: "报告生成时间",
    generatedBy: "生成人",
    analysisIntro: "本报告基于当前数据对团队在人员、时间和任务分类三个维度上的表现进行综合分析。",
    personnelAnalysis: "人员维度分析",
    timeAnalysis: "时间维度分析",
    categoryAnalysis: "分类维度分析",
    dataManagement: "数据管理",
    batchManage: "批量管理",
    selectAll: "全选",
    taskDetailList: "人员任务详情",
    searchTasks: "搜索任务...",
    notifications: "消息通知",
    noNotifications: "暂无新通知",
    markAllRead: "全部已读",
    taskAssigned: "新任务分配",
    taskUpdated: "任务状态更新",
    taskOverdue: "任务逾期提醒",
    taskUpcoming: "任务即将开始",
    taskDeleted: "任务已删除",
    userCompletedTask: "人员已完成任务",
    userUpdatedTask: "人员更新了任务",
    dueTomorrow: "将于明日截止。",
    isOverdue: "已逾期，请尽快处理！",
    accountPending: "账号等待管理员审批中。",
    accountRejected: "账号申请已被拒绝。",
    sessionLimit: "同时在线设备已达上限 (3)。",
    approve: "通过",
    reject: "拒绝",
    pendingApproval: "待审批",
    userStatus: "状态",
    resetSessions: "重置会话",
    sessions: "会话",
    regSuccessWait: "注册申请已提交！请等待管理员审批。",
    changeRole: "修改角色",
    userRole: "用户权限",
    // Comments
    tabDetails: "任务详情",
    tabComments: "管理评价",
    comments: "评价与反馈",
    noComments: "暂无评价。",
    writeComment: "写下您的评价...",
    send: "发送",
    postedBy: "发布人",
    dailyOverdueSummaryTitle: "每日逾期汇总",
    dailyOverdueSummaryBody: (count: number) => `截止目前，您有 ${count} 项任务已逾期，请及时处理。`,
    passwordChangedRelogin: "密码修改成功，请重新登录。",
    sessionExpired: "会话已超时，请重新登录。",
  }
};

export const INITIAL_USERS: User[] = [];

export const INITIAL_TASKS: Task[] = [
  {
    id: 't1',
    employeeId: '1001',
    category: 'Network Optimization',
    title: 'Site Survey',
    description: 'Survey site A for 5G deployment',
    startDate: new Date().toISOString().split('T')[0],
    endDate: new Date().toISOString().split('T')[0],
    status: 'pending'
  }
];
